"""add expiry_date to products

Revision ID: 191810979140
Revises: 11ae19393635
Create Date: 2025-01-19 11:22:45.853948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191810979140'
down_revision = '11ae19393635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###
